# Generated by Django 3.1.2 on 2021-05-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_city', models.CharField(blank=True, max_length=50, null=True)),
                ('state_code', models.CharField(blank=True, max_length=50, null=True)),
                ('state_name', models.CharField(blank=True, max_length=20, null=True)),
                ('dist_code', models.CharField(blank=True, max_length=20, null=True)),
                ('population_total', models.CharField(blank=True, max_length=20, null=True)),
                ('population_male', models.CharField(blank=True, max_length=20, null=True)),
                ('population_female', models.CharField(blank=True, max_length=20, null=True)),
                ('population_total_0to6', models.CharField(blank=True, max_length=20, null=True)),
                ('population_male_0to6', models.CharField(blank=True, max_length=20, null=True)),
                ('population_female_0to6', models.CharField(blank=True, max_length=20, null=True)),
                ('literates_total', models.CharField(blank=True, max_length=20, null=True)),
                ('literates_male', models.CharField(blank=True, max_length=20, null=True)),
                ('literates_female', models.CharField(blank=True, max_length=20, null=True)),
                ('sex_ratio', models.CharField(blank=True, max_length=20, null=True)),
                ('child_sex_ratio', models.CharField(blank=True, max_length=20, null=True)),
                ('effective_literacy_rate_total', models.CharField(blank=True, max_length=20, null=True)),
                ('effective_literacy_rate_male', models.CharField(blank=True, max_length=20, null=True)),
                ('effective_literacy_rate_female', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('total_graduates', models.CharField(blank=True, max_length=20, null=True)),
                ('male_graduates', models.CharField(blank=True, max_length=20, null=True)),
                ('female_graduates', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'cities',
                'managed': False,
            },
        ),
    ]
