# Generated by Django 3.1.2 on 2021-05-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_city', models.CharField(blank=True, max_length=50, null=True)),
                ('state_code', models.CharField(blank=True, max_length=50, null=True)),
                ('state_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dist_code', models.CharField(blank=True, max_length=50, null=True)),
                ('population_total', models.CharField(blank=True, max_length=50, null=True)),
                ('population_male', models.CharField(blank=True, max_length=50, null=True)),
                ('population_female', models.CharField(blank=True, max_length=50, null=True)),
                ('population_total0to6', models.CharField(blank=True, max_length=50, null=True)),
                ('population_male0to6', models.CharField(blank=True, max_length=50, null=True)),
                ('population_female0to6', models.CharField(blank=True, max_length=50, null=True)),
                ('literates_total', models.CharField(blank=True, max_length=50, null=True)),
                ('literates_male', models.CharField(blank=True, max_length=50, null=True)),
                ('literates_female', models.CharField(blank=True, max_length=50, null=True)),
                ('sex_ratio', models.CharField(blank=True, max_length=50, null=True)),
                ('child_sex_ratio', models.CharField(blank=True, max_length=50, null=True)),
                ('effective_literacy_rate_total', models.CharField(blank=True, max_length=50, null=True)),
                ('effective_literacy_rate_male', models.CharField(blank=True, max_length=50, null=True)),
                ('effective_literacy_rate_female', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('total_graduates', models.CharField(blank=True, max_length=50, null=True)),
                ('male_graduates', models.CharField(blank=True, max_length=50, null=True)),
                ('female_graduates', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'demography',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Graduates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_graduates', models.CharField(blank=True, max_length=50, null=True)),
                ('male_graduates', models.CharField(blank=True, max_length=50, null=True)),
                ('female_graduates', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'graduates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LiteracyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_literacy_rate_total', models.CharField(blank=True, max_length=50, null=True)),
                ('effective_literacy_rate_male', models.CharField(blank=True, max_length=50, null=True)),
                ('effective_literacy_rate_female', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'literacy_rate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Literates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literates_total', models.CharField(blank=True, max_length=50, null=True)),
                ('literates_male', models.CharField(blank=True, max_length=50, null=True)),
                ('literates_female', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'literates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population_total', models.CharField(blank=True, max_length=50, null=True)),
                ('population_male', models.CharField(blank=True, max_length=50, null=True)),
                ('population_female', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'population',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Population0To6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population_total0to6', models.CharField(blank=True, max_length=50, null=True)),
                ('population_male0to6', models.CharField(blank=True, max_length=50, null=True)),
                ('population_female0to6', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'population0to6',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ratio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex_ratio', models.CharField(blank=True, max_length=50, null=True)),
                ('child_sex_ratio', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ratio',
                'managed': False,
            },
        ),
    ]
