# Generated by Django 3.1.2 on 2021-05-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_demography_graduates_literacyrate_literates_population_population0to6_ratio'),'0001_initial'
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Demography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_city', models.CharField(blank=True, max_length=50, null=True)),
                ('state_code', models.CharField(blank=True, max_length=50, null=True)),
                ('state_name', models.CharField(blank=True, max_length=50, null=True)),
                ('dist_code', models.CharField(blank=True, max_length=50, null=True)),
                ('population_total', models.CharField(blank=True, max_length=50, null=True)),
                ('population_male', models.CharField(blank=True, max_length=50, null=True)),
                ('population_female', models.CharField(blank=True, max_length=50, null=True)),
                ('population_total0to6', models.CharField(blank=True, max_length=50, null=True)),
                ('population_male0to6', models.CharField(blank=True, max_length=50, null=True)),
                ('population_female0to6', models.CharField(blank=True, max_length=50, null=True)),
                ('literates_total', models.CharField(blank=True, max_length=50, null=True)),
                ('literates_male', models.CharField(blank=True, max_length=50, null=True)),
                ('literates_female', models.CharField(blank=True, max_length=50, null=True)),
                ('sex_ratio', models.CharField(blank=True, max_length=50, null=True)),
                ('child_sex_ratio', models.CharField(blank=True, max_length=50, null=True)),
                ('effective_literacy_rate_total', models.CharField(blank=True, max_length=50, null=True)),
                ('effective_literacy_rate_male', models.CharField(blank=True, max_length=50, null=True)),
                ('effective_literacy_rate_female', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('total_graduates', models.CharField(blank=True, max_length=50, null=True)),
                ('male_graduates', models.CharField(blank=True, max_length=50, null=True)),
                ('female_graduates', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'demography',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Graduates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_graduates', models.CharField(blank=True, max_length=50, null=True)),
                ('male_graduates', models.CharField(blank=True, max_length=50, null=True)),
                ('female_graduates', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'graduates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LiteracyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_literacy_rate_total', models.CharField(blank=True, max_length=50, null=True)),
                ('effective_literacy_rate_male', models.CharField(blank=True, max_length=50, null=True)),
                ('effective_literacy_rate_female', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'literacy_rate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Literates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literates_total', models.CharField(blank=True, max_length=50, null=True)),
                ('literates_male', models.CharField(blank=True, max_length=50, null=True)),
                ('literates_female', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'literates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population_total', models.CharField(blank=True, max_length=50, null=True)),
                ('population_male', models.CharField(blank=True, max_length=50, null=True)),
                ('population_female', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'population',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Population0To6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population_total0to6', models.CharField(blank=True, max_length=50, null=True)),
                ('population_male0to6', models.CharField(blank=True, max_length=50, null=True)),
                ('population_female0to6', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'population0to6',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ratio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex_ratio', models.CharField(blank=True, max_length=50, null=True)),
                ('child_sex_ratio', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ratio',
                'managed': False,
            },
        ),
    ]
